apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onlyadditionalproperties.example.com
spec:
  group: example.com
  names:
    kind: OnlyAdditionalProperties
    singular: onlyadditionalproperties
    plural: onlyadditionalproperties
    shortNames:
      - oap
    categories:
      - oap
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              additionalProperties:
                type: object
                properties:
                  value:
                    type: string
